using Entidades;
using LogicaNegocio;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Interfaz.Administración_Tickets
{
    public partial class ModificarTickets : Form
    {
        Ticket ticket;
        Usuario usuarioActual;
        Ticketslogica logica = new Ticketslogica();

        public ModificarTickets(Ticket ticket, Usuario usuarioActual)
        {
            InitializeComponent();
            this.ticket = ticket;
            this.usuarioActual = usuarioActual;
            // This line of code is generated by Data Source Configuration Wizard
            listaComentariosTableAdapter1.Fill(conexionComentarios1.ListaComentarios);
        }

        private void ModificarTickets_Load(object sender, EventArgs e)
        {
            cbxEstado.Items.Add("Pendiente");
            cbxEstado.Items.Add("Proceso");
            cbxEstado.Items.Add("Completado");

            txt_nombTicket.Text = ticket.nombre_ticket;
            txtUsuarioSolicita.Text = ticket.correo_solicita;
            txtUsuarioTecnico.Text = ticket.usuario_atiende;
            txtTipo.Text = ticket.tipo_ticket;
            txtPrioridad.Text = ticket.prioridad;
            txt_comentario.Text = ticket.comentarios;
            cbxEstado.Text = ticket.estado;
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            Dashboard dash = new Dashboard(usuarioActual);
            dash.Show();
            this.Close();
        }

        private void btnGuardar_Click(object sender, EventArgs e)
        {
            if(cbxEstado.SelectedItem == null)
            {
                logica.EditarTicket(ticket.id_ticket, cbxEstado.Text);
            }
            else
            {
                logica.EditarTicket(ticket.id_ticket, cbxEstado.SelectedItem.ToString());
            }
            MessageBox.Show("Ticket Actualizado");
            Dashboard dash = new Dashboard(usuarioActual);
            dash.Show();
            this.Close();
        }

        private void filtrar(object sender, EventArgs e)
        {
            for (int i = 0; i < listaComentarios.RowCount; i++)
            {
                if (!listaComentarios.GetRowCellValue(i, "Ticket ID").ToString().Equals(ticket.id_ticket.ToString()))
                {
                    listaComentarios.DeleteRow(i);
                }
            }
        }

        private void btnAgregarComentario_Click(object sender, EventArgs e)
        {
            CrearComentario crear = new CrearComentario(ticket,usuarioActual);
            crear.Show();
            this.Close();
        }
    }
}
