using Entidades;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Interfaz.Administración_Usuarios;
using LogicaNegocio;
using Interfaz.Administración_Tickets;

namespace Interfaz
{
    public partial class Dashboard : DevExpress.XtraEditors.XtraForm
    {
        Usuario usuarioActual;
        Ticketslogica logicaTicket = new Ticketslogica();

        public Dashboard(Usuario usuario)
        {
            InitializeComponent();
            usuarioActual = usuario;
            // This line of code is generated by Data Source Configuration Wizard
            listaTicketsActivosTableAdapter1.Fill(ticketsActivos1.ListaTicketsActivos);
        }



        private void tileBar_SelectedItemChanged(object sender, TileItemEventArgs e)
        {
            navigationFrame.SelectedPageIndex = tileBarGroupTables.Items.IndexOf(e.Item);
        }

        private void btnUsuario_Click(object sender, EventArgs e)
        {
            CrearUsuario nuevo = new CrearUsuario(usuarioActual);
            nuevo.Show();
        }

      

        private void btnCreaTicket_Click(object sender, EventArgs e)
        {
            CreaTickets crear = new CreaTickets(usuarioActual);
            crear.Show();
            this.Close();
        }

        private void btnCreaDpt_Click(object sender, EventArgs e)
        {
            CrearDepartamento dpt = new CrearDepartamento(usuarioActual);
            dpt.Show();
        }

        private void btnModificar_Click(object sender, EventArgs e)
        {
            ModificarUsuario modificar = new ModificarUsuario(usuarioActual);
            modificar.Show();
        }

        private void editarTicket(object sender, EventArgs e)
        {
            string nombre = listaTickets.GetRowCellValue(listaTickets.FocusedRowHandle, "Nombre").ToString();
            string creacion = listaTickets.GetRowCellValue(listaTickets.FocusedRowHandle, "Creacion").ToString();
            string tipo = listaTickets.GetRowCellValue(listaTickets.FocusedRowHandle, "Tipo").ToString();
            if (nombre.Equals(""))
            {
                MessageBox.Show("Favor seleccione un ticket", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                if (logicaTicket.BuscarTicket(nombre,creacion,tipo) != null)
                {
                    Ticket edicion = logicaTicket.BuscarTicket(nombre, creacion, tipo);
                    ModificarTickets editar = new ModificarTickets(edicion, usuarioActual);
                    editar.Show();
                    this.Close();
                }
                else
                {
                    MessageBox.Show("Algo raro");
                }
            }
        }
    }
}